#!/bin/bash
for file in *.svg; do
	filename=$(basename -- "$file")
	filename="${filename%.*}"
	#set filename $(basename -- "$file")
	#set filename "${filename%.*}"
	convert -background transparent -define 'icon:auto-resize=128' "$file" "../ico-128x128/$filename".ico

done





















